<html>
<head> 
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">

</head>
<body>
	<main>
		<h2 style="color:royalblue">Sonic Project Leaderboard </h2>

		<a href="index.phtml"> Retour</a>

		<table>
			<caption style="font-size:1.5rem;color:darkgrey">Liste de scores </caption>
			<tr> 
				<th>Pseudo</th>
				<th>Score</th>

			</tr>
			<?php foreach( $users as $user):?>

				

				<tr>

					<th><?=$user["pseudo"]?></th>
					<th> <?=$user["score"]?></th>

				</tr>
			<?php endforeach;?>


		</table>

	</main>
</body>
</html>